# Generated by Django 3.0.3 on 2020-03-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_desc', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
