# Generated by Django 3.0.3 on 2020-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0002_auto_20200416_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('person_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=100)),
                ('person_email', models.CharField(max_length=100)),
                ('person_phone', models.CharField(max_length=100)),
                ('person_EID', models.CharField(max_length=100)),
                ('person_Query', models.CharField(max_length=1000)),
            ],
        ),
    ]
