# Generated by Django 3.0.3 on 2020-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0004_auto_20200416_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='person_phone',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
