# Generated by Django 3.0.3 on 2020-04-16 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0005_auto_20200416_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='person_phone',
            field=models.IntegerField(default=datetime.datetime(2020, 4, 16, 15, 18, 56, 813287, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
