# Generated by Django 3.0.3 on 2020-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0006_auto_20200416_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='person_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
