# Generated by Django 3.0.3 on 2020-04-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0007_auto_20200416_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='person_id',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
