# Generated by Django 3.0.3 on 2020-04-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0008_auto_20200416_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
