# Generated by Django 3.0.3 on 2020-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0009_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(default='', max_length=100)),
                ('person_email', models.CharField(default='', max_length=100)),
                ('person_phone', models.IntegerField()),
                ('person_EID', models.CharField(default='', max_length=100)),
                ('person_Query', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
