# Generated by Django 3.0.3 on 2020-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0011_remove_contact_us_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='person_phone',
            field=models.IntegerField(null=True),
        ),
    ]
