# Generated by Django 3.0.3 on 2020-04-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0012_contact_us_person_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
