# Generated by Django 3.0.3 on 2020-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0014_inform'),
    ]

    operations = [
        migrations.CreateModel(
            name='INFORMation',
            fields=[
                ('ID1', models.AutoField(primary_key=True, serialize=False)),
                ('name2', models.CharField(default='', max_length=50)),
                ('Email3', models.CharField(default='', max_length=50)),
                ('phone4', models.IntegerField()),
                ('Eid5', models.TextField(max_length=20)),
                ('Query6', models.CharField(max_length=1000)),
            ],
        ),
    ]
