# Generated by Django 3.0.3 on 2020-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0015_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='phone4',
            field=models.IntegerField(null=True),
        ),
    ]
