# Generated by Django 3.0.3 on 2020-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0016_auto_20200416_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Eid5',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='information',
            name='Query6',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone4',
            field=models.IntegerField(),
        ),
    ]
