# Generated by Django 3.0.3 on 2020-04-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0017_auto_20200416_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='phone4',
        ),
    ]
