# Generated by Django 3.0.3 on 2020-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0018_remove_information_phone4'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='phone4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
