# Generated by Django 3.0.3 on 2020-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0021_auto_20200416_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='phone4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
