# Generated by Django 3.0.3 on 2020-04-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0022_auto_20200416_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INFORMation',
        ),
    ]
