# Generated by Django 3.0.3 on 2020-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0023_delete_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('Person_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PERSON_NAME', models.CharField(default='', max_length=30)),
                ('PERSON_EMAIL', models.CharField(default='', max_length=50)),
                ('PERSON_EID', models.CharField(max_length=20)),
                ('PERSON_PHONE', models.IntegerField(default=0)),
                ('PERSON_QUERY', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='INFORM',
        ),
    ]
