# Generated by Django 3.0.3 on 2020-04-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0024_auto_20200416_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain',
            new_name='Complain1',
        ),
        migrations.RenameField(
            model_name='complain1',
            old_name='PERSON_EID',
            new_name='PERSON_EID1',
        ),
        migrations.RenameField(
            model_name='complain1',
            old_name='PERSON_EMAIL',
            new_name='PERSON_EMAIL1',
        ),
        migrations.RenameField(
            model_name='complain1',
            old_name='PERSON_NAME',
            new_name='PERSON_NAME1',
        ),
        migrations.RenameField(
            model_name='complain1',
            old_name='PERSON_PHONE',
            new_name='PERSON_PHONE1',
        ),
        migrations.RenameField(
            model_name='complain1',
            old_name='PERSON_QUERY',
            new_name='PERSON_QUERY1',
        ),
        migrations.RenameField(
            model_name='complain1',
            old_name='Person_ID',
            new_name='Person_ID1',
        ),
    ]
