# Generated by Django 3.0.3 on 2020-04-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0025_auto_20200416_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain1',
        ),
    ]
