# Generated by Django 3.0.3 on 2020-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0026_delete_complain1'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHOBOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=60)),
                ('Eid', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=3000)),
            ],
        ),
    ]
