# Generated by Django 3.0.3 on 2020-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0029_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
