# Generated by Django 3.0.3 on 2020-04-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0032_orders_item_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
