# Generated by Django 3.0.3 on 2020-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartmain', '0033_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=220),
        ),
    ]
