# Generated by Django 3.0.3 on 2020-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('Head0', models.CharField(max_length=250)),
                ('Head1', models.CharField(max_length=250)),
                ('Head2', models.CharField(max_length=250)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='Ecartblog/image')),
            ],
        ),
    ]
