# Generated by Django 3.0.3 on 2020-04-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecartblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentHead0',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='contentHead1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='contentHead2',
            field=models.CharField(default='', max_length=250),
        ),
    ]
